version: "3.9"

networks:
  jojo:
    name: jojo 

services:
  
  api:
  
    build: api
    
    container_name: jojo-api
    
    volumes:
      - ./api:/api
    
    ports:
      - "5000:5000"
    
    networks:
      - jojo
