version: "3.9"

networks:
  jojo:
    name: jojo 

services:
  
  postgre:
    image: mongo:5.0
    
    restart: on-failure

    container_name: mongo
    
    hostname: mongo

    networks:
      - jojo

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


