version: "3.9"

services:
  api:
    build: api
    container_name: jojo-api
    environment:
      FLASK_APP: jojo
      FLASK_HOST: 0.0.0.0
      FLASK_ENV: development
    volumes:
      - ./api:/api
    ports:
      - "5000:5000"
    networks:
      - jojo

networks:
  jojo:
    name: jojo
